[project]
name = "Knowledge-Mixing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.2.0",
    "python-dotenv>=1.1.1",
    "polars>=1.31.0",
    "tabulate>=0.9.0",
    "transformers>=4.57.1",
]
