[project]
name = "Knowledge-Generation"
version = "0.1.0"
description = "A project for generation of synthetic data"
requires-python = ">=3.12"
dependencies = [
    "sdg-hub>=0.6.0",
    "datasets>=3.6.0",
    "python-dotenv>=1.1.1"
]
