[project]
name = "03-model-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "training-hub[cuda]>=0.3.0",
    "transformers>=4.57.1",
    "python-dotenv>=1.1.1"
]
