[project]
name = "01-data-preprocessing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.2.0",
    "docling>=2.53.0",
    "markdown-it-py>=4.0.0",
    "pathlib>=1.0.1",
    "tiktoken>=0.11.0",
]

